### ISSUE TITLE
Error due to missing -o option in samtools sort

### ISSUE THREAD

**Issue by inti** [cauyrd/transIndel#3]
https://github.com/cauyrd/transIndel/blob/8c1b981561438a8f7cf54283afa4d2e3bbc479e3/transIndel_build_RNA.py#L201

On a test I got this error `[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files` . I think it is solved by adding `-o` to the output file. It may also be nice to allow users to specify the `-T` option to liaise with local implementation of temporary folders

**Comment by cauyrd** [comment]
Yes, I will get the code updated soon to have this feature.

**Comment by wvandegeer** [comment]
Kudos on the tool. 
Along the same lines as the fix above.. I think a previous samtools version supported the lack of `-o` and that it also used to add the '.bam' after the name. 

I added the `-o` myself and then it exits due to an incorrect file name.
`Command 'mv test.temp.sorted.bam test.bam' returned non-zero exit status 1`.
Like I mentioned, it doesn't add the '.bam' after the file name. This would be the ideal fix in my opinion:
`subprocess.check_call("samtools sort "+output+".temp.bam -o "+output+".temp.sorted.bam", shell=True)`

**Comment by csijcs** [comment]
Hello, is there a solution to this problem? I have just tried running using the -o option and am getting a similar error:
`Command 'samtools sort test.temp.bam test.temp.sorted' returned non-zero exit status 1`

**Comment by cauyrd** [comment]
We have update this transIndel and solved this issue. The new version need to use Samtools 1.0 or newer to run tranindel. Please check it and let us know any further issue.

**Comment by csijcs** [comment]
Hello,


Yes, I am using samtools 1.7 and still getting this issue


On Oct 4, 2018, at 9:33 PM, Rendong Yang <notifications@github.com> wrote:


We have update this transIndel and solved this issue. The new version need to use Samtools 1.0 or newer to run tranindel. Please check it and let us know any further issue.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cauyrd/transIndel","title":"cauyrd/transIndel","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png" class="">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png" class="">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/cauyrd/transIndel" class="">https://github.com/cauyrd/transIndel</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cauyrd in #3: We have update this transIndel and solved this issue. The new version need to use Samtools 1.0 or newer to run tranindel. Please check it and let us know any further issue."}],"action":{"name":"View Issue","url":"<a href="https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252" class="">https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252</a>"}}}[
{
"@context": "<a href="http://schema.org" class="">http://schema.org</a>",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "<a href="https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252" class="">https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252</a>",
"url": "<a href="https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252" class="">https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252</a>",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "<a href="https://github.com" class="">https://github.com</a>"
}
},
{
"@type": "MessageCard",
"@context": "<a href="http://schema.org/extensions" class="">http://schema.org/extensions</a>",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cauyrd/transIndel] Error due to missing -o option in samtools sort (#3)",
"sections": [
{
"text": "",
"activityTitle": "**Rendong Yang**",
"activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png" class="">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>",
"activitySubtitle": "@cauyrd",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "<a href="https://api.github.com" class="">https://api.github.com</a>",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cauyrd/transIndel\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "<a href="https://api.github.com" class="">https://api.github.com</a>",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"cauyrd/transIndel\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "<a href="https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252" class="">https://github.com/cauyrd/transIndel/issues/3#issuecomment-427020252</a>"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "<a href="https://api.github.com" class="">https://api.github.com</a>",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375379135\n}"
}
],
"themeColor": "26292E"
}
]







Important: This email is confidential and may be privileged. If you are not the intended recipient, please delete it and notify us immediately; you should not copy or use it for any purpose, nor disclose its contents to any other person. Thank you.

**Comment by cauyrd** [comment]
we testing the code and it works for samtools 1.7. Have you re-download the
newest version? If you keep having problems, let me know you error message.
